---
title: "EMODnet Biology robis demo"
output:
html_document: default
html_notebook: default
---

## Install the robis package

robis is not available on CRAN. It needs to be installed from GitHub. In the devtools package, you will find the function install_github() which does the installation for you. If devtools is not yet installed on your machine, do that first.

```{r installation, echo=TRUE, message=FALSE, warning=FALSE}
is_installed <- function(mypkg) is.element(mypkg, installed.packages()[,1])
if(!is_installed("devtools"))  install.packages("devtools")
if(!is_installed("robis"))  devtools::install_github("iobis/robis")
if(!is_installed("leaflet"))  install.packages("leaflet")
if(!is_installed("tidyverse"))  install.packages("tidyverse")
if(!is_installed("rworldxtra"))  install.packages("rworldxtra")
library(robis)
library(leaflet)
library(tidyverse)
library(rworldxtra)
```

## Download occurence data from OBIS

### By scientific name

```{r plotLeafletmap}
df <- occurrence(scientificname = c("Phaeocystis"), geometry = "POLYGON ((2 50,2 55, 10 55, 10 50, 2 50))")
#"POLYGON ((2.3 51, 2.3 56, 8 56, 8 51,2.3 51))")

map_leaflet(df)
```







Use the leaflet package

```{r plotLeaflet}
leaflet(df) %>% addTiles() %>% addCircleMarkers(lat = ~decimalLatitude, lng = ~decimalLongitude, clusterOptions = markerClusterOptions()) 
```


```{r}

df$scientificName <- as.factor(df$scientificName)

pal <- colorFactor(
  palette = "Accent",
  domain = df$scientificName
)


leaflet(df) %>%
  addTiles(group = "OSM (default)") %>%
  addProviderTiles("Hydda.Base", group = "Hydda.Base") %>%
  addProviderTiles("Esri.WorldImagery", group = "Esri.WorldImagery") %>%
  addWMSTiles("http://ows.emodnet-bathymetry.eu/wms",
              layers = "emodnet:mean_multicolour",
              options = WMSTileOptions(version = "1.3.0", format="image/png", transparent = T),
              group = "EMODnet bathymetry") %>%
  addWMSTiles("http://geodata.nationaalgeoregister.nl/natura2000/ows",
              layers = "natura2000",
              options = WMSTileOptions(version = "1.3.0", format="image/png", transparent = T, EPSG = "28992"), group = "Natura2000") %>%
  addProviderTiles("OpenSeaMap", group = "OpenSeaMap") %>%
  addCircleMarkers(lat = ~decimalLatitude, 
                   lng = ~decimalLongitude,
                   radius = 3,
                   color  = ~pal(scientificName),
                   label = ~paste(scientificName, year)
                   ) %>%
  addLayersControl(
    baseGroups = c("OSM (default)", "Hydda.Base", "Esri.WorldImagery"),
    overlayGroups =  c("EMODnet bathymetry", "OpenSeaMap", "observations", "Natura2000")
  ) %>%
  hideGroup(c("EMODnet bathymetry", "OpenSeaMap", "Natura2000"))


```


Or plot using ggplot


```{r plotGGplot, echo=FALSE, message=FALSE, warning=FALSE}
b = 2
data("countriesHigh")
world <- fortify(countriesHigh)
ggplot(data = df, aes(decimalLongitude, decimalLatitude)) +
  geom_polygon(data = world, aes(x = long, y = lat, group = group), fill = "darkgrey") +
  geom_point(aes(color = scientificName)) +
  # coord_quickmap(
  #   xlim = range(data$decimalLongitude), 
  #   ylim = range(data$decimalLatitude)
  # ) +
  coord_map(projection = "ortho",
            orientation = c(mean(df$decimalLatitude), mean(df$decimalLongitude), 0),
            xlim =  expand_scale(range(df$decimalLongitude), c(-4,10)) ,
            ylim = expand_scale(range(df$decimalLatitude), c(50, 60))
            )
```



```{r plotTimeSeries}

df %>% 
  group_by(scientificName, year) %>%
  summarize(sum = n()) %>%
  summary()



df %>% 
  group_by(scientificName, year) %>%
  summarize(sum = n()) %>%
  mutate(year = as.integer(year)) %>%
  ggplot (aes(x = year, y = sum)) + 
  geom_point(aes(color = scientificName), size = 2)


```




